### ISSUE TITLE
bpm job fails when removing links

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#706]
When using an ops-file to remove the database link from uaa:

```
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/consumes?
  value: {database: nil}
```

I get the following error:

```
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa Error: recovered in f: interface conversion: interface {} is string, not map[string]interface {}
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa goroutine 1 [running]:
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa runtime/debug.Stack(0xc0005013b8, 0x14956a0, 0xc00023d980)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/cmd/internal.glob..func2.1(0xc000501d80)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/bpm_configs.go:43 +0x141
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa panic(0x14956a0, 0xc00023d980)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.generateJobConsumersData(0xc0000b8700, 0xc00091f080, 0xc00091f0b0, 0xc0001acfeb, 0x3)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:318 +0x63c
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).processConsumers(0xc000156b40, 0x0, 0x0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:160 +0x13c
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).resolveManifest(0xc000156b40, 0x0, 0x22ef7c8)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:94 +0x74
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).BPMConfigs(0xc000156b40, 0x16, 0xc000046016, 0x6)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:50 +0x51
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/cmd/internal.glob..func2(0x22bfa40, 0x22ef7c8, 0x0, 0x0, 0x0, 0x0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/bpm_configs.go:104 +0x42c
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa github.com/spf13/cobra.(*Command).execute(0x22bfa40, 0xc00003a1a0, 0x0, 0x0, 0x22bfa40, 0xc00003a1a0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa github.com/spf13/cobra.(*Command).ExecuteC(0x22bff40, 0x40576f, 0xc0000aa058, 0x0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa github.com/spf13/cobra.(*Command).Execute(...)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/cmd/internal.Execute()
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/root.go:130 +0x2d
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa main.main()
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/cf-operator/main.go:6 +0x20
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa Sleeping ...
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 2019/11/15 02:26:01 recovered in f: interface conversion: interface {} is string, not map[string]interface {}
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa goroutine 1 [running]:
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa runtime/debug.Stack(0xc0005013b8, 0x14956a0, 0xc00023d980)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/cmd/internal.glob..func2.1(0xc000501d80)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/bpm_configs.go:43 +0x141
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa panic(0x14956a0, 0xc00023d980)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.generateJobConsumersData(0xc0000b8700, 0xc00091f080, 0xc00091f0b0, 0xc0001acfeb, 0x3)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:318 +0x63c
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).processConsumers(0xc000156b40, 0x0, 0x0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:160 +0x13c
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).resolveManifest(0xc000156b40, 0x0, 0x22ef7c8)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:94 +0x74
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).BPMConfigs(0xc000156b40, 0x16, 0xc000046016, 0x6)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:50 +0x51
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/cmd/internal.glob..func2(0x22bfa40, 0x22ef7c8, 0x0, 0x0, 0x0, 0x0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/bpm_configs.go:104 +0x42c
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa github.com/spf13/cobra.(*Command).execute(0x22bfa40, 0xc00003a1a0, 0x0, 0x0, 0x22bfa40, 0xc00003a1a0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa github.com/spf13/cobra.(*Command).ExecuteC(0x22bff40, 0x40576f, 0xc0000aa058, 0x0)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa github.com/spf13/cobra.(*Command).Execute(...)
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa code.cloudfoundry.org/cf-operator/cmd/internal.Execute()
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/root.go:130 +0x2d
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa main.main()
bpm-kubecf-68d02b40f523c3d7-njkt9 uaa 	/go/src/code.cloudfoundry.org/cf-operator/cmd/cf-operator/main.go:6 +0x20
```

This happens when applying the external database ops-file https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-external-dbs.yml#L269-L271.

**Comment by edwardstudy** [comment]
It's an interface conversion issue when generating job consumers.
